import Head from 'next/head'
import Image from 'next/image'
import Timeline from '../Modules/Timeline/timeline'
import styles from '../styles/Home.module.css'
import moment from 'moment';
import data from '../Modules/dataset'
import React, {Component} from "react";


const props = {
    initialGroups: [],
    initialItems: data.data,
    options: {
        start: data.start_date,
        end: data.end_date,
        height: '300px',
        rtl: true,
        orientation: 'top',
        editable: true,
        zoomMax: 1000 * 60 * 60 * 24 * 31 * 12 * 5,
    }
};

const now = moment().minutes(0).seconds(0).milliseconds(0);


class Demo extends Component {
    timelineRef = React.createRef();


    render() {
        return (


            <div className={styles.container}>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>

                <main className={styles.main}>
                    <h1>Demo</h1>
                    <div className="app">
                        <p className="header">This example demonstrate using groups.</p>
                        <div className="timeline-container">
                            <Timeline
                                ref={this.timelineRef}
                                {...props}
                            />
                        </div>
                        <br/>
                    </div>
                </main>

                <footer className={styles.footer}>
                    <a
                        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        target="_blank"
                        rel="noopener noreferrer">
                        Powered by{' '}
                        <span className={styles.logo}><Image src="/vercel.svg" alt="Vercel Logo" width={72}
                                                             height={16}/></span>
                    </a>
                </footer>
            </div>
        );
    }
}

module.exports = Demo